## **Project title**:- `healtcare disease analysis and prediction system.`
## **records**:- `10,000 rows`
## **Machine Learning Model** :- `Random forest.`

## Importing the all required libraries:-

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score , confusion_matrix,recall_score,f1_score

## **load the dataset**:-

In [2]:
df = pd.read_csv("health_dataset_10000_rows.csv")
df.head()

,patient_id,age,sex,bmi,blood_pressure,glucose_level,cholesterol,heart_rate,smoking,family_history,physical_activity,sleep_hours,disease_prediction
0,10001,71.00,Female,39.21,135.0,104.0,134.0,71.0,No,No,Moderate,7.1,No
1,10002,29.00,Female,24.00,127.0,124.0,197.0,62.0,No,No,Low,6.9,No
2,10003,19.00,Male,18.80,142.0,138.0,186.0,83.0,No,No,Low,4.1,No
3,10004,58.00,Female,24.50,104.0,109.0,172.0,61.0,No,Yes,Moderate,7.7,No
4,10005,48.78,Female,28.20,95.0,127.0,154.0,85.0,No,No,Moderate,5.1,No

## **Insights**:-
- here i cleaned the data in EDA so we don't need to clean the data.

## **Encoding**:-
- we convert the categorical columns into the numeric using the label encoding.

In [3]:
# call labelencoder:-
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])
df["smoking"] = le.fit_transform(df["smoking"])
df["family_history"] = le.fit_transform(df["family_history"])
df["physical_activity"] = le.fit_transform(df["physical_activity"])

In [4]:
df.head()

,patient_id,age,sex,bmi,blood_pressure,glucose_level,cholesterol,heart_rate,smoking,family_history,physical_activity,sleep_hours,disease_prediction
0,10001,71.00,0,39.21,135.0,104.0,134.0,71.0,0,0,2,7.1,No
1,10002,29.00,0,24.00,127.0,124.0,197.0,62.0,0,0,1,6.9,No
2,10003,19.00,1,18.80,142.0,138.0,186.0,83.0,0,0,1,4.1,No
3,10004,58.00,0,24.50,104.0,109.0,172.0,61.0,0,1,2,7.7,No
4,10005,48.78,0,28.20,95.0,127.0,154.0,85.0,0,0,2,5.1,No

## **Insights**:-
- here we converted the categorical columns into numerical using the labelencode.

## we don't need of the patient_id so we drop the patient_columnn.

In [5]:
df = df.drop("patient_id",axis = 1)

In [6]:
df.head()

,age,sex,bmi,blood_pressure,glucose_level,cholesterol,heart_rate,smoking,family_history,physical_activity,sleep_hours,disease_prediction
0,71.00,0,39.21,135.0,104.0,134.0,71.0,0,0,2,7.1,No
1,29.00,0,24.00,127.0,124.0,197.0,62.0,0,0,1,6.9,No
2,19.00,1,18.80,142.0,138.0,186.0,83.0,0,0,1,4.1,No
3,58.00,0,24.50,104.0,109.0,172.0,61.0,0,1,2,7.7,No
4,48.78,0,28.20,95.0,127.0,154.0,85.0,0,0,2,5.1,No

## **defining the features and target**:-

In [7]:
x = df.drop("disease_prediction",axis = 1)
y = df["disease_prediction"]

## **Insights**:-
- we defined the all features as x and the "disease_prediction" as the target

## Spliting the features and target into train test split to train the model

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 46)

In [9]:
## checking the splited data shape:-
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 11)
(2000, 11)
(8000,)
(2000,)

## **Insights**:-
- so here we can see our data is splited using the `train_test_split` into training and testing section.

## **Features scaling**:-
- we scale the all features data into in one range to get best performance.

In [10]:
## calling the scaler:- 
scaler = StandardScaler()
x_train_scl = scaler.fit_transform(x_train)
x_test_scl = scaler.fit_transform(x_test)

In [11]:
x_train_scl

array([[-1.60150689, -0.90362073,  1.53319455, ..., -0.67047592,
         0.91631845, -0.81880159],
       [-0.14988979, -0.90362073,  2.26970798, ..., -0.67047592,
        -1.63033696, -1.67115949],
       [-1.54567546, -0.90362073,  1.79868195, ..., -0.67047592,
        -1.63033696, -0.56309422],
       ...,
       [ 0.01760449, -0.90362073,  1.13710448, ..., -0.67047592,
        -0.35700926,  0.88591421],
       [ 0.68758161, -0.90362073, -2.20503931, ..., -0.67047592,
         0.91631845, -0.64833001],
       [-1.09902405, -0.90362073, -0.88830746, ..., -0.67047592,
        -0.35700926, -1.24498054]], shape=(8000, 11))

In [12]:
x_test_scl

array([[-1.60264004,  1.09886556, -0.52142043, ...,  1.55150089,
        -1.67272629,  0.77788424],
       [-0.6453808 ,  1.09886556, -0.28128127, ..., -0.64453717,
         0.90069877,  1.44991814],
       [ 1.43806578, -0.91002943,  0.80874172, ..., -0.64453717,
        -0.38601376, -0.14616237],
       ...,
       [-0.25121523, -0.91002943,  2.33727969, ..., -0.64453717,
        -0.38601376, -2.24626831],
       [ 0.98759084,  1.09886556, -1.63023691, ...,  1.55150089,
        -1.67272629, -0.73419204],
       [-0.1385965 ,  1.09886556, -0.0411421 , ..., -0.64453717,
         0.90069877, -0.14616237]], shape=(2000, 11))

## **Insights**:- 
- here we can see the of my data is scaled into the one range.

## **Training model**:- (`Random Forest`)

In [13]:
random_f = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    max_depth=10,
    min_samples_leaf=5,
    random_state=42)
random_f.fit(x_train_scl,y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_leaf=5, n_estimators=200, random_state=42)

## Making prediction:-

In [14]:
pred = random_f.predict(x_test_scl)
comp = pd.DataFrame({
    "actual prediction" : y_test,
    "model prediction" : pred
})
comp

     actual prediction model prediction
1909                No               No
4189                No               No
5819               Yes              Yes
8449                No               No
6501                No               No
...                ...              ...
2587               Yes              Yes
6379                No               No
4566                No               No
9087               Yes              Yes
6311               Yes              Yes

[2000 rows x 2 columns]

## **Insights**:-
- we trained the model.
- we make prediction and compared it with actual values.

## **Evaluation**:-

In [15]:
## calling all parameters to evaluate the model(accuracy_score,confusion_matrix):-
Accuracy = accuracy_score(y_test,pred)
cm = confusion_matrix(y_test,pred)

In [16]:
print(Accuracy*100,"%")
print(cm)

94.5 %
[[1448   65]
 [  45  442]]

## **Insights**:- 
- here we can see the our model is giving the `94.5%` accuracy which is best.

In [17]:
import joblib

In [18]:
joblib.dump(random_f,"ML_MODEL_D.pkl")

['ML_MODEL_D.pkl']